{
  "errorName": "UserAlreadyExistsException",
  "cause": "null",
  "errorMsg": "Email already exists!"
}